#!/bin/bash

PEGGED=../Pegged

if [[ ! -d "$PEGGED" ]]; then
    echo To run this example, you need to clone Pegged.
    echo
    echo pushd ..
    echo git clone https://github.com/PhilippeSigaud/Pegged.git
    echo popd
    exit 1
fi

if [[ "$#" -ne 1 ]]; then
    echo "Usage: basic <filename>" >&2
    exit 2
fi

BASIC_NAME=$(basename -- "$1")
MODULE_NAME="${BASIC_NAME%.*}"
D_NAME="$MODULE_NAME.d"

rm -f "$D_NAME"

echo "import compiler;"                    >> "$D_NAME"
echo "mixin(compile!(\"$BASIC_NAME\"));"   >> "$D_NAME"

dmd -J=. "$D_NAME" source/compiler.d "$PEGGED"/pegged/*.d "$PEGGED"/pegged/dynamic/*.d
